services:
    OHMedia\SecurityBundle\EventListener\BlameableSubscriber:
        arguments: ["@security.token_storage"]
        tags: ["doctrine.event_subscriber"]

    OHMedia\SecurityBundle\Command\BoilerplateCommand:
        arguments: ["%kernel.project_dir%"]
        tags: ["console.command"]

    OHMedia\SecurityBundle\Twig\BootstrapExtension:
        tags: ["twig.extension"]
