services:
    OHMedia\SecurityBundle\EventListener\BlameableSubscriber:
        arguments: ["@security.token_storage"]
        tags: ["doctrine.event_subscriber"]

    OHMedia\SecurityBundle\Command\BoilerplateCommand:
        arguments: ["%kernel.project_dir%"]
        tags: ["console.command"]

    OHMedia\SecurityBundle\Command\CreateUserCommand:
        autowire: true
        tags: ["console.command"]

    OHMedia\SecurityBundle\Controller\LoginController:
        tags: ["controller.service_arguments"]
        calls:
            - method: setContainer
              arguments: ["@service_container"]

    OHMedia\SecurityBundle\Controller\PasswordController:
        tags: ["controller.service_arguments"]
        calls:
            - method: setContainer
              arguments: ["@service_container"]

    OHMedia\SecurityBundle\Controller\VerificationController:
        tags: ["controller.service_arguments"]
        calls:
            - method: setContainer
              arguments: ["@service_container"]

    OHMedia\SecurityBundle\Form\UserType:
        arguments: ["%oh_media_timezone.timezone%"]
        tags: ["form.type"]

    OHMedia\SecurityBundle\Repository\UserRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    OHMedia\SecurityBundle\Security\Voter\UserVoter:
        tags: ["security.voter"]
