services:
    OHMedia\SecurityBundle\Service\Blamer:
        arguments: ["@security.token_storage"]

    oh_media_security.blamer:
        alias: OHMedia\SecurityBundle\Service\Blamer

    OHMedia\SecurityBundle\EventListener\BlamePrePersist:
        arguments: ["@oh_media_security.blamer"]
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'prePersist'

    OHMedia\SecurityBundle\EventListener\BlamePreUpdate:
        arguments: ["@oh_media_security.blamer"]
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'preUpdate'

    OHMedia\SecurityBundle\Command\CreateUserCommand:
        autowire: true
        tags: ["console.command"]

    OHMedia\SecurityBundle\Controller\LoginController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Controller\PasswordController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Controller\UserController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Controller\VerificationController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    oh_media_security.entity_choice_manager:
        class: OHMedia\SecurityBundle\Service\EntityChoiceManager

    OHMedia\SecurityBundle\Form\UserType:
        arguments: ["@oh_media_security.entity_choice_manager", "%oh_media_timezone.timezone%"]
        tags: ["form.type"]

    OHMedia\SecurityBundle\Repository\UserRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    OHMedia\SecurityBundle\Security\Voter\UserVoter:
        tags: ["security.voter"]

    OHMedia\SecurityBundle\Service\UserNavItemProvider:
        autowire: true
        tags: ["oh_media_backend.nav_item_provider"]
