services:
    oh_media_security.twig.entity_extension:
        class: OHMedia\SecurityBundle\Twig\EntityExtension
        arguments: ["@router", "@security.authorization_checker"]
        tags:
            - { name: twig.extension }

    oh_media_security.form.type.actions:
        class: OHMedia\SecurityBundle\Form\Type\ActionsType
        tags:
            - { name: form.type }

    oh_media_security.blameable_subscriber:
        class: OHMedia\SecurityBundle\EventListener\BlameableSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber }

    oh_media_security.provider_handler:
        class: OHMedia\SecurityBundle\Provider\ProviderHandler
        arguments:
            - !tagged_iterator oh_media_security.provider

    OHMedia\SecurityBundle\Command\BoilerplateCommand:
        arguments: ["%kernel.project_dir%"]
        tags: ["console.command"]
