services:
    jstnthms_security.twig.entity_extension:
        class: JstnThms\SecurityBundle\Twig\EntityExtension
        arguments: ["@router", "@security.authorization_checker"]
        tags:
            - { name: twig.extension }
    
    jstnthms_security.form.type.actions:
        class: JstnThms\SecurityBundle\Form\Type\ActionsType
        tags:
            - { name: form.type }
    
    jstnthms_security.timezone_listener:
        class: JstnThms\SecurityBundle\EventListener\TimezoneListener
        arguments: ["@security.token_storage", "%jstnthms_security.timezone%"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    
    jstnthms_security.blameable_subscriber:
        class: JstnThms\SecurityBundle\EventListener\BlameableSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber }
    
    jstnthms_security.provider_handler:
        class: JstnThms\SecurityBundle\Provider\ProviderHandler
        arguments:
            - !tagged_iterator jstnthms_security.provider
