services:
    OHMedia\SecurityBundle\Service\Blamer:
        arguments: ["@security.token_storage"]

    ohmedia_security.blamer:
      alias: OHMedia\SecurityBundle\Service\Blamer

    OHMedia\SecurityBundle\EventListener\BlamePrePersist:
        arguments: ["@ohmedia_security.blamer"]
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'prePersist'

    OHMedia\SecurityBundle\EventListener\BlamePreUpdate:
        arguments: ["@ohmedia_security.blamer"]
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'preUpdate'

    OHMedia\SecurityBundle\Command\BoilerplateCommand:
        arguments: ["%kernel.project_dir%"]
        tags: ["console.command"]

    OHMedia\SecurityBundle\Command\CreateUserCommand:
        autowire: true
        tags: ["console.command"]

    OHMedia\SecurityBundle\Controller\LoginController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Controller\PasswordController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Controller\VerificationController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Form\UserType:
        arguments: ["%oh_media_timezone.timezone%"]
        tags: ["form.type"]

    OHMedia\SecurityBundle\Repository\UserRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    OHMedia\SecurityBundle\Security\Voter\UserVoter:
        tags: ["security.voter"]
