services:
    OHMedia\SecurityBundle\Command\CreateUserCommand:
        autowire: true
        tags: ["console.command"]

    OHMedia\SecurityBundle\Controller\LoginController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Controller\PasswordController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Controller\ProfileController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Controller\UserController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Controller\VerificationController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\SecurityBundle\Service\EntityChoiceManager:
        autowire: true

    oh_media_security.entity_choice_manager: '@OHMedia\SecurityBundle\Service\EntityChoiceManager'

    OHMedia\SecurityBundle\Form\UserType:
        arguments: ["@oh_media_security.entity_choice_manager", "%oh_media_timezone.timezone%"]
        tags: ["form.type"]

    OHMedia\SecurityBundle\Form\ProfileType:
        arguments: ["%oh_media_timezone.timezone%"]
        tags: ["form.type"]

    OHMedia\SecurityBundle\Repository\UserRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    OHMedia\SecurityBundle\Security\Voter\UserVoter:
        tags: ["security.voter"]

    OHMedia\SecurityBundle\Service\UserNavItemProvider:
        autowire: true
        tags: ["oh_media_backend.nav_item_provider"]

    OHMedia\SecurityBundle\Twig\EntityChoiceExtension:
        autowire: true
        tags: ["twig.extension"]

    OHMedia\SecurityBundle\Service\UserLifecycle:
        autowire: true
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'OHMedia\SecurityBundle\Entity\User'
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'OHMedia\SecurityBundle\Entity\User'
